name: Build/Release Cherry Studio

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install corepack
        run: corepack enable && corepack prepare yarn@4.3.1 --activate

      - name: Install Dependencies
        run: yarn install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: yarn build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: yarn build:win

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.CHERRY_STUDIO_TOKEN }}
